/*
 Copyright © 1998, 2014, Oracle and/or its affiliates.  All rights reserved.
*/
var QueryStringArray=[],QueryXref=[],isNav6=false,isNav4=false;function GotoReportList(){document.location.href="../KP_ODS/List.aspx";return false}function ExitKP(a){document.location.href=a+"/Common/Logout.aspx"}function GetWindowWidth(){var a;a=window.innerWidth?window.innerWidth:document.body.clientWidth;if(a<=0)a=0;return a}
if(parseInt(navigator.appVersion.charAt(0))>=4){var VersionInfo;if(navigator.appName=="Netscape"){VersionInfo=navigator.appVersion.split(" ");if(VersionInfo[0]>4.08)if(VersionInfo[0]>=5)isNav6=true;else isNav4=true}isIE4=navigator.appName.indexOf("Microsoft")!=-1?true:false}function QueryString(a,b){this.name=a;this.value=b;QueryXref[a]=QueryStringArray.length}function QueryStringObj(a){return QueryStringArray[QueryXref[a]]?QueryStringArray[QueryXref[a]].value:""}
function GetQueryStringArray(a){var b,c;b=a.indexOf("?");if(b<0)b=a.indexOf("#");if(b>=0){a=a.substr(b+1);b=a.split("&");for(var d=0;d<b.length;d++){var e=b[d];c=e.indexOf("=");a=e.substr(0,c);c=e.substr(c+1);QueryStringArray[d]=new QueryString(a,c)}}}function UPK_GetContext(){return UPKContextID}var arrFirstTierLangs=["DE","EN","ES","FR","JA","NL"];function IsFirstTierLang(a){for(var b=0;b<arrFirstTierLangs.length;b++)if(a.toUpperCase()==arrFirstTierLangs[b])return true;return false}
function UPK_GetApplicableCddUrls(){var a,b=HelpLang;switch(HelpID){case "PortalHelp":a="KCenter";break;case "ReportHelp":a="Reports";IsFirstTierLang(b)||(b="en");break;case "ManagerHelp":a="Manager";IsFirstTierLang(b)||(b="en");break;default:a="KCenter"}return Array(document.location.href.split("/",4).join("/")+"/Public/cdd/cdd.html?help="+a+"&lang="+b)}
function DisplayHelp(a,b,c){var d,e;d=a;e=Math.round(screen.width/2-400);intTop=Math.round(screen.height/2-300);e="left="+e+", top="+intTop+", width=800, height=550, help=no, status=no, toolbar=no, menubar=no, directories=no, location=no, scrollbars=yes, resizable=yes";switch(b){case "PortalHelp":a=PortalHelpURL;break;case "ReportHelp":b=ReportLangInclude.split(",");(a=LangIncludeInList(b,a.toLowerCase()))||(d=DefaultLanguage);a=ReportHelpURL;break;case "ManagerHelp":b=ManagerLangInclude.split(",");
(a=LangIncludeInList(b,a.toLowerCase()))||(d=DefaultLanguage);a=ManagerHelpURL;break;default:a=PortalHelpURL}b="?";if(a.indexOf("?")!=-1)b="&";if(a.substr(0,1)=="/")a=c+a;c=document.getElementsByTagName("meta");for(var g,f=0;f<c.length;f++)if(c[f].name=="upk-namespace")g=c[f].content;a+=b+"lang="+d+"&namespace="+g+"&context="+UPK_GetContext();d=window.open(a,"KPHelp",e);d.focus();return d}
function DisplayHelp_old(a,b,c){var d;alert("Display help for the following context - "+UPK_GetContext());d=Math.round(screen.width/2-400);intTop=Math.round(screen.height/2-300);switch(a){case "de":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_501.htm&StartNode="+b+"&NoMax=1";break;case "en":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_336.htm&StartNode="+b+"&NoMax=1";break;case "es":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_281.htm&StartNode="+b+"&NoMax=1";break;case "fr":a=
c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_391.htm&StartNode="+b+"&NoMax=1";break;case "hu":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_556.htm&StartNode="+b+"&NoMax=1";break;case "it":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_446.htm&StartNode="+b+"&NoMax=1";break;case "ja":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_831.htm&StartNode="+b+"&NoMax=1";break;case "nl":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_611.htm&StartNode="+b+"&NoMax=1";break;
case "pl":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_666.htm&StartNode="+b+"&NoMax=1";break;case "pt":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_721.htm&StartNode="+b+"&NoMax=1";break;case "ru":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_776.htm&StartNode="+b+"&NoMax=1";break;case "zh-chs":a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_886.htm&StartNode="+b+"&NoMax=1";break;default:a=c+a+"/"+a+"/Offline/Course/frCourse.htm?URL=0_10037_336.htm&StartNode="+b+"&NoMax=1"}d=
window.open(a,"KPHelp","left="+d+", top="+intTop+", width=800, height=550, help=no, status=no, toolbar=no, menubar=no, directories=no, location=no, scrollbars=yes, resizable=yes");d.focus();return d}
function DisplayUTHelp(a,b,c){a=Math.round(screen.width/2-400);intTop=Math.round(screen.height/2-300);c=window.open(c+"/index.html","KPHelp","left="+a+", top="+intTop+", width=800, height=550, help=no, status=no, toolbar=no, menubar=no, directories=no, location=no, scrollbars=yes, resizable=yes");c.focus();return c}
function OpenNewScrollWindow(a,b,c,d){window.open(c,d,"left="+Math.round(screen.width/2-a/2)+", top="+Math.round(screen.height/2-b/2)+", channelmode=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,toolbar=no,width="+a+",height="+b)}function set_cookie(a,b,c){document.cookie=a+"="+escape(b)+(c==null?"":"; expires="+c.toGMTString())+"; path="+GetTopPath()+";"}
function get_cookie(a){a+="=";if(document.cookie.length>0){offset=document.cookie.indexOf(a);if(offset!=-1){offset+=a.length;end=document.cookie.indexOf(";",offset);if(end==-1)end=document.cookie.length;return unescape(document.cookie.substring(offset,end))}else return""}else return""}function NavToHome(){window.location.href="../Default.aspx"}
function GetTopPath(){var a,b;a=document.location.pathname;b=a.lastIndexOf("/");a=a.substr(0,b-1);b=a.lastIndexOf("/");a=a.substr(0,b-1);b=a.lastIndexOf("/");return a=a.substr(0,b)}function GetCurrentURLPath(){strPath=document.location.pathname;intLastPos=strPath.lastIndexOf("/");strPath=strPath.substr(0,intLastPos-1);intLastPos=strPath.lastIndexOf("/");strPath=strPath.substr(0,intLastPos);return strPath=document.location.protocol+"//"+document.location.host+strPath+"/"}
function IsUnsignedInteger(a){return a.search(/^[0-9]+$/)==0}function InitBanner(){var a=document.getElementById("header1table"),b=document.getElementById("bannerimg");if(a&&b)b.style.height=""+a.clientHeight+"px";Resize_General();window.onresize=Resize_General}function Resize_General(){setTimeout("_Resize_General()",0)}
function _Resize_General(){if(document.body.clientHeight<100||document.body.clientWidth<100)return false;var a=document.getElementById("myTableToc"),b=document.getElementById("header1table"),c=document.getElementById("thorizontal1");if(a!=null&&b!=null&&c!=null){h=document.body.clientHeight-c.clientHeight*2-b.clientHeight;if(h>=0)a.style.height=""+h+"px"}}function PtToPx(a,b){return Math.round(a*b/72)};var _simulate_120_dpi=false;function IsTouchDevice(){return upk.browserInfo.isTouchDevice()}var upk=upk||{};
(function(a){var b="",c,d=false,e,g=false,f=false;a.getAgentInfo=function(){return typeof document.documentMode!="undefined"?navigator.userAgent+" - "+document.documentMode:navigator.userAgent};a.isSupportedBrowser=function(){var k=false;if(b=="MSIE"&&(c>=8||d&&e>=4))k=true;if(b=="Firefox"&&(c==24||c>=27))k=true;if(b=="Safari"&&c>=6)k=true;if(b=="Chrome"&&c>=32)k=true;if(a.isiOS())k=true;return k};a.isHardStop=function(){return b=="MSIE"&&c<=6};a.isMacOs=function(){return g};a.isFF3=function(){return f};
a.isFF=function(){return b=="Firefox"};a.isFF4=function(){return b=="Firefox"&&c==4};a.checkFFVersion=function(k){return b=="Firefox"&&c==k};a.isSafari=function(){return b=="Safari"||b=="Chrome"};a.isChrome=function(){return b=="Chrome"};a.isExplorer=function(){return b=="MSIE"};a.isIEVersion=function(k){return b=="MSIE"&&c==k};a.isIEQuirks=function(){if(a.isExplorer()==false)return false;return document.compatMode!=="CSS1Compat"};a.isIE8=function(){if(b!="MSIE")return false;return c==8&&d&&e==4};
a.isIE9=function(){if(b!="MSIE")return false;if(c==9&&d&&e==5)return true;if(c==7&&d&&e==5)return true;return d&&e==6&&(c!=10||document.documentMode!=10)};a.isIE10=function(){if(b!="MSIE")return false;return c==10&&d&&e==6&&document.documentMode==10};a.isIE10orHigher=function(){if(b!="MSIE")return false;return c>=10&&d&&e>=6&&document.documentMode>=10};a.isIE11=function(){if(b!="MSIE")return false;return c==11&&d&&e==7&&document.documentMode==11};a.isIE11Compatibility=function(){if(b!="MSIE")return false;
return d&&e==7&&(c!=11||document.documentMode!=11)};a.isActiveXEnabled=function(){var k=null,m="";try{new ActiveXObject("")}catch(n){m=n.name}try{k=!!new ActiveXObject("htmlfile")}catch(o){k=false}return m!="ReferenceError"&&k==false?false:true};a.isIE10Modern=function(){if(a.isIE10()==false)return false;return!a.isActiveXEnabled()};a.isiOS=function(){var k=navigator.platform;if(k==="iPad"||k==="iPad Simulator"||k==="iPhone"||k==="iPod")return true;return false};a.isiOS5=function(){return navigator.userAgent.indexOf("CPU OS 5_")>=
0};a.isiOS6=function(){return navigator.userAgent.indexOf("CPU OS 6_")>=0};a.isiOS7=function(){return navigator.userAgent.indexOf("CPU OS 7_")>=0};a.isTouchDevice=function(){if(a.isChrome())return null;return window.Touch||window.navigator.msMaxTouchPoints};a.isSoundSupported=function(){if(a.isiOS())return true;if(window.location.href.substr(0,7).toLowerCase()=="file://")return false;if(swfobject.getFlashPlayerVersion().major>0)return true;return false};var i=navigator.userAgent,j=-1;if(i.indexOf("OPR")>=
0){b="Opera";j=i.indexOf("OPR")+4}else if(i.indexOf("Chrome")>=0){b="Chrome";j=i.indexOf("Chrome")+7}else if(i.indexOf("Opera")>=0){b="Opera";j=i.indexOf("Opera")+6}else if(i.indexOf("Firefox")>=0){b="Firefox";j=i.indexOf("Firefox")+8}else if(i.indexOf("Safari")>=0){b="Safari";j=i.indexOf("Version")+8}else if(i.indexOf("MSIE")>=0){b="MSIE";j=i.indexOf("MSIE")+5;var l=i.indexOf("Trident/");if(l>=0){d=true;e=parseInt(i.substr(l+8))}}else if(i.indexOf(" rv:")>=0){b="MSIE";j=i.indexOf(" rv:")+3;l=i.indexOf("Trident/");
if(l>=0){d=true;e=parseInt(i.substr(l+8))}}else{b="";c=0}if(b!=""){c=parseInt(i.substr(j));if(isNaN(c)){j++;c=parseInt(i.substr(j))}parseInt(i.substr(j+2,1))}if(b=="Safari"&&isNaN(c))c=5;g=i.indexOf("Macintosh")>=0;f=b=="Firefox"&&i.indexOf("Firefox/3")>0})(upk.browserInfo={});function getDIV(a){return document.getElementById(a)}function getDIVstyle(a){try{return document.getElementById(a).style}catch(b){return null}}function shiftTo(a,b,c){a=getDIVstyle(a);a.left=b+"px";a.top=c+"px"}
function getUniWidth(a){return a.offsetWidth}function getUniHeight(a){return a.offsetHeight}function getClientWidth(a){return a.offsetWidth}function getClientHeight(a){return a.offsetHeight}function getObjHeight(a){return getDIV(a).offsetHeight}function getObjWidth(a){return getDIV(a).offsetWidth}function getObjLeft(a){try{var b=getDIVstyle(a);return b.pixelLeft?b.pixelLeft:b.left!=""?parseInt(b.left):document.getElementById(a).offsetLeft}catch(c){return parseInt(a.offsetLeft)}}
function getObjTop(a){try{var b=getDIVstyle(a);return b.pixelTop?b.pixelTop:b.top!=""?parseInt(b.top):document.getElementById(a).offsetTop}catch(c){return parseInt(a.offsetTop)}}function getInsideWindowWidth(){return window.innerWidth?window.innerWidth:document.body.clientWidth}function getInsideWindowHeight(){return window.innerHeight?window.innerHeight:document.body.clientHeight}
function getScrollLeft(){return window.pageXOffset||window.pageXOffset==0?window.pageXOffset:document.body.scrollLeft}function getScrollTop(){return window.pageYOffset||window.pageYOffset==0?window.pageYOffset:document.body.scrollTop}function show(a,b){getDIVstyle(a).visibility="visible";if(b&&upk.browserInfo.isiOS())try{playMode=="S"&&showActObj.type=="Input"&&$("#"+a+" input").attr("readonly",true)}catch(c){}}function hide(a){getDIVstyle(a).visibility="hidden"}var __DPIwidth=0;
function getDpiInfo(){var a=document.getElementById("DPIInfoDiv");if(a!=null){__DPIwidth=a.clientWidth;if(__DPIwidth==0)__DPIwidth=96;__DPIwidth!=0&&document.getElementsByTagName("body")[0].removeChild(a)}return _simulate_120_dpi==true?120:__DPIwidth}function initDpiInfo(){document.write('<div id="DPIInfoDiv" style="visibility:hidden; width: 72pt; height: 1pt;">DPIINFODIV</div>')}function checkIEDPI(){return true}function Get_Element(a){return document.getElementById(a)}
function touch(a){if(a.originalEvent.touches&&a.originalEvent.touches.length)return a.originalEvent.touches[0];else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)return a.originalEvent.changedTouches[0]}function isNavBar(){return typeof navBar!=="undefined"};function Course(){this.PostassessRequiredScore=this.PostassessRequired=this.PreassessAllowPlaceout=this.PreassessRequiredScore=this.PreassessRequired=this.AllowPersonal=this.PlayMode=this.SubjectRequired=this.HasPostAssess=this.HasCourse=this.HasPreAssess=this.StartPersonal=this.LOXref=this.LOArray=this.Postassess=this.Preassess=this.Playmode=this.HasAssessmentCompleted=this.HideGUINext=this.HideGUIPrev=this.DeliveryNodeResultDate=this.DeliveryNodeID=this.CourseLearningObjectID=null;this.RollupProcess=
new RollupProcess(this);this.SequencingProcess=new SequencingProcess(this)}Course.prototype.OverallRollupProcess=Course_OverallRollupProcess;Course.prototype.StartSequencingProcess=Course_StartSequencingProcess;Course.prototype.FindPrevItem=Course_FindPrevItem;Course.prototype.FindNextItem=Course_FindNextItem;Course.prototype.FindFirstItem=Course_FindFirstItem;Course.prototype.FindLastItem=Course_FindLastItem;Course.prototype.FindChoiceItem=Course_FindChoiceItem;
Course.prototype.IsPrevOrNextItem=Course_IsPrevOrNextItem;Course.prototype.IsAncestorOrSelf=Course_IsAncestorOrSelf;function Course_OverallRollupProcess(a,b,c,d,e){this.RollupProcess.ExtendedOverallRollupProcess(a,b,c,d,e)}function Course_StartSequencingProcess(){this.SequencingProcess.StartSequencingProcess()}
function Course_FindPrevItem(){if(this.DeliveryNodeID==""||this.DeliveryNodeID=="I")this.FindFirstItem();else{var a;if(this.HasPreAssess==true&&this.DeliveryNodeID.length>4&&this.DeliveryNodeID.substring(0,4)=="PRE_")return this.FindFirstItem();else a=this.HasPostAssess==true&&this.DeliveryNodeID.length>5&&this.DeliveryNodeID.substring(0,5)=="POST_"?this.LOArray.length:this.LOXref["K_"+this.DeliveryNodeID];if(this.HasCourse==true&&a-1>=0)for(a-=1;a>=0;a--)if(this.LOArray[a].Enabled==true&&this.LOArray[a].Skip==
false&&this.LOArray[a].ChildrenNodeIDs.length==0)return this.LOArray[a].NodeID;if(this.HasPreAssess==true)if(this.Preassess.Enabled==true&&this.Preassess.Skip==false)return this.Preassess.NodeID;return this.FindFirstItem()}}
function Course_FindNextItem(){if(this.DeliveryNodeID==""||this.DeliveryNodeID=="I")return this.FindFirstItem();else{var a;if(this.HasPreAssess==true&&this.DeliveryNodeID.length>4&&this.DeliveryNodeID.substring(0,4)=="PRE_")a=-1;else if(this.HasPostAssess==true&&this.DeliveryNodeID.length>5&&this.DeliveryNodeID.substring(0,5)=="POST_")return"";else a=this.LOXref["K_"+this.DeliveryNodeID];if(this.HasCourse==true&&this.LOArray.length>=a+1)for(a+=1;a<this.LOArray.length;a++)if(this.LOArray[a].Enabled==
true&&this.LOArray[a].Skip==false&&this.LOArray[a].ChildrenNodeIDs.length==0)return this.LOArray[a].NodeID;if(this.HasPostAssess==true)if(this.Postassess.Enabled==true&&this.Postassess.Skip==false)return this.Postassess.NodeID;return""}}
function Course_FindFirstItem(){if(this.HasPreAssess==true)if(this.Preassess.Enabled==true&&this.Preassess.Skip==false)return this.Preassess.NodeID;if(this.HasCourse==true)for(var a=0;a<this.LOArray.length;a++)if(this.LOArray[a].Enabled==true&&this.LOArray[a].Skip==false&&this.LOArray[a].ChildrenNodeIDs.length==0)return this.LOArray[a].NodeID;if(this.HasPostAssess==true)if(this.Postassess.Enabled==true&&this.Postassess.Skip==false)return this.Postassess.NodeID;return""}
function Course_FindLastItem(){if(this.HasPostAssess==true)if(this.Postassess.Enabled==true&&this.Postassess.Skip==false)return this.Postassess.NodeID;if(this.HasCourse==true)for(var a=this.LOArray.length-1;a>=0;a--)if(this.LOArray[a].Enabled==true&&this.LOArray[a].Skip==false&&this.LOArray[a].ChildrenNodeIDs.length==0)return this.LOArray[a].NodeID;if(this.HasPreAssess==true)if(this.Preassess.Enabled==true&&this.Preassess.Skip==false)return this.Preassess.NodeID;return""}
function Course_FindChoiceItem(a){if(a.length>4&&a.substring(0,4)=="PRE_"||a.length>5&&a.substring(0,5)=="POST_"||this.LOArray[LOXref["K_"+a]].ChildrenNodeIDs.length==0)return a;else{for(a=this.LOXref["K_"+a];a<this.LOArray.length;a++)if(this.LOArray[a].Enabled==true&&this.LOArray[a].Skip==false&&this.LOArray[a].ChildrenNodeIDs.length==0)return this.LOArray[a].NodeID;return""}}
function Course_IsPrevOrNextItem(a){if(this.DeliveryNodeID==""||this.DeliveryNodeID=="I"){var b=this.FindFirstItem();return this.IsAncestorOrSelf(a,b)?true:false}b=this.FindPrevItem();if(this.IsAncestorOrSelf(a,b))return true;b=this.FindNextItem();if(this.IsAncestorOrSelf(a,b))return true;return false}
function Course_IsAncestorOrSelf(a,b){if(b==a)return true;if(b.length>4&&b.substring(0,4)=="PRE_")return false;if(b.length>5&&b.substring(0,4)=="POST_")return false;if(this.LOArray[LOXref["K_"+b]].GUID.substring(0,2)=="C_")if(this.LOArray[LOXref["K_"+a]].GUID.substring(2)==this.LOArray[LOXref["K_"+b]].GUID.substring(2))return true;return false};function LO(a,b,c,d,e,g,f,i,j,l,k,m,n,o,p,q,r,s,t,u,v){this.NodeID=a;this.LearningObjectID=b;this.GUID=d;this.AssessType=c;this.ParentLearningObjectID=e;this.OriginalPlacement=g;this.ResourceType=f;this.NodeType=i;this.CompletionStatus=j;this.ProgressMeasure=l;this.SuccessStatus=k;this.ScoreScaled=m;this.IsPersonalContentItem=n;this.PersonalOBJSuccessStatus=o;this.Visible=p;this.Skip=q;this.HiddenFromChoice=r;this.Enabled=s;this.VisibleChildrenCount=t;this.IsLastChild=u;this.ChildrenNodeIDs=v;LOXref["K_"+
a]=A.length;this.TotalLeafNodesInBranch=0;this.DataDirty=false}LO.prototype.GetTotalLeafNodesInBranch=LO_GetTotalLeafNodesInBranch;LO.prototype.SetEnabled=LO_SetEnabled;function LO_GetTotalLeafNodesInBranch(){if(this.TotalLeafNodesInBranch==0){var a=0;if(this.ChildrenNodeIDs.length>0)for(var b=0;b<lo.ChildrenNodeIDs.length;b++){var c=A[LOXref["K_"+ChildrenNodeIDs[b]]];c.GetTotalLeafNodesInBranch();a+=c.TotalLeafNodesInBranch}else a=1;this.TotalLeafNodesInBranch=a}}
function LO_SetEnabled(a){this.Enabled=a;if(this.ChildrenNodeIDs.length>0)for(var b=0;b<this.ChildrenNodeIDs.length;b++)A[LOXref["K_"+this.ChildrenNodeIDs[b]]].SetEnabled(a)};function RollupProcess(a){this.Course=a}RollupProcess.prototype.ExtendedOverallRollupProcess=RollupProcess_ExtendedOverallRollupProcess;RollupProcess.prototype.OverallRollupProcess=RollupProcess_OverallRollupProcess;RollupProcess.prototype.GetPath=RollupProcess_GetPath;RollupProcess.prototype.ProgressMeasureRollupProcessDefault=RollupProcess_ProgressMeasureRollupProcessDefault;RollupProcess.prototype.ActivityProgressRollupProcessDefault=RollupProcess_ActivityProgressRollupProcessDefault;
function RollupProcess_ExtendedOverallRollupProcess(a,b,c){var d=0;if(a.length>4&&a.substring(0,4)=="PRE_"){d=1;parseInt(a.substring(4))}else if(a.length>5&&a.substring(0,5)=="POST_"){d=2;parseInt(a.substring(5))}else{d=0;parseInt(a)}if(d==0){d=[];d[0]=this.Course.LOArray[this.Course.LOXref["K_"+a]];for(var e=d[0].GUID,g=0,f=0;f<this.Course.LOArray.length;f++)if(this.Course.LOArray[f].GUID==e&&this.Course.LOArray[f].NodeID!=a){g++;d[g]=this.Course.LOArray[f]}for(f=0;f<=g;f++){if(d[f].CompletionStatus!=
1)d[f].CompletionStatus=b;if(!((d[f].SuccessStatus==1||d[f].SuccessStatus==2)&&c!=1&&c!=2))d[f].SuccessStatus=c}for(f=0;f<=g;f++)d[f].ParentLearningObjectID!=0&&d[f].LearningObjectID!=this.Course.CourseLearningObjectID&&this.OverallRollupProcess(d[f].ParentLearningObjectID);this.ProgressMeasureRollupProcessDefault(this.Course.LOArray[this.Course.LOXref["K_"+this.Course.CourseLearningObjectID]])}else if(d==1){this.Course.Preassess.CompletionStatus=b;this.Course.Preassess.SuccessStatus=c}else if(d==
2){this.Course.Postassess.CompletionStatus=b;this.Course.Postassess.SuccessStatus=c}}function RollupProcess_OverallRollupProcess(a){a=this.GetPath(a);if(a.length!=0)for(var b=0;b<a.length;b++)this.ActivityProgressRollupProcessDefault(this.Course.LOArray[this.Course.LOXref["K_"+a[b]]])}
function RollupProcess_GetPath(a){var b=[],c=0;for(b[0]=a;this.Course.LOArray[this.Course.LOXref["K_"+a]].LearningObjectID!=this.Course.CourseLearningObjectID;){a=this.Course.LOArray[this.Course.LOXref["K_"+a]].ParentLearningObjectID;c++;b[c]=a}return b}
function RollupProcess_ActivityProgressRollupProcessDefault(a){var b=3;if(a.ChildrenNodeIDs.length!=0){for(var c=false,d=false,e=false,g=0;g<a.ChildrenNodeIDs.length;g++){var f=this.Course.LOArray[this.Course.LOXref["K_"+a.ChildrenNodeIDs[g]]];if(!(this.Course.StartPersonal==true&&f.IsPersonalContentItem==1&&f.PersonalOBJSuccessStatus==1))if(f.CompletionStatus==1)c=true;else if(f.CompletionStatus==2)d=true;else e=true}if(d==false&&c==false)b=3;else if(e==true)b=2;else if(d==true)b=2;else if(c==true)b=
1;if(a.CompletionStatus>b)a.CompletionStatus=b}}function RollupProcess_ProgressMeasureRollupProcessDefault(a){var b=0,c=0;if(a.ChildrenNodeIDs.length!=0){for(var d=0;d<this.Course.LOArray.length;d++)if(this.Course.LOArray[d].ChildrenNodeIDs.length==0&&this.Course.LOArray[d].Skip==0){c+=1;if(this.Course.LOArray[d].CompletionStatus==1)b+=1}a.ProgressMeasure=c!=0?b/c:1}if(a.CompletionStatus==1)a.ProgressMeasure=1};function SequencingProcess(a){this.Course=a}SequencingProcess.prototype.StartSequencingProcess=SequencingProcess_StartSequencingProcess;SequencingProcess.prototype.ApplyPrecondition_PreassessmentTakenOnlyOnce=SequencingProcess_ApplyPrecondition_PreassessmentTakenOnlyOnce;SequencingProcess.prototype.ApplyPrecondition_PreassessmentRequired=SequencingProcess_ApplyPrecondition_PreassessmentRequired;SequencingProcess.prototype.ApplyPrecondition_CourseRequired=SequencingProcess_ApplyPrecondition_CourseRequired;
function SequencingProcess_StartSequencingProcess(){this.ApplyPrecondition_PreassessmentTakenOnlyOnce();this.ApplyPrecondition_PreassessmentRequired()&&this.ApplyPrecondition_CourseRequired()}function SequencingProcess_ApplyPrecondition_PreassessmentTakenOnlyOnce(){if(this.Course.Preassess!=null)if(this.Course.Preassess.CompletionStatus==1){this.Course.Preassess.Enabled=0;this.Course.Preassess.Skip=1}}
function SequencingProcess_ApplyPrecondition_PreassessmentRequired(){var a=true;if(this.Course.Preassess!=null)if(this.Course.PreassessRequired==true)if(this.Course.Preassess.CompletionStatus==1){a=true;this.Course.HasCourse==true&&this.Course.LOArray[this.Course.LOXref["K_"+this.Course.CourseLearningObjectID]].SetEnabled(1)}else a=false;return a}
function SequencingProcess_ApplyPrecondition_CourseRequired(){if(this.Course.HasCourse==true&&this.Course.SubjectRequired==true)if(this.Course.LOArray[this.Course.LOXref["K_"+this.Course.CourseLearningObjectID]].CompletionStatus!=1){if(this.Course.Postassess!=null)if(this.Course.Preassess!=null&&this.Course.PreassessRequiredScore!=0)this.Course.Preassess.SuccessStatus==1?this.Course.Postassess.SetEnabled(1):this.Course.Postassess.SetEnabled(0);else this.Course.Postassess.SetEnabled(0)}else this.Course.Postassess!=
null&&this.Course.Postassess.SetEnabled(1)};var PostOutlineCookie=true,InactivityTimeoutID=0,OutlineTime=new Date,NavTime=new Date,sepX,sepPrevX,IsFirefox=false,ua=navigator.userAgent.toLowerCase();if(ua.indexOf("mozilla")!=-1)if(ua.indexOf("firefox")!=-1)IsFirefox=true;
function GetOutlineWidth(){var a;if(_blnIncludeOutline){_blnShowOutline=get_cookie("ShowOutline_"+document.frmParams.elements.UserID.value);if(_blnShowOutline!=""){a=get_cookie("OutlineWidth_"+document.frmParams.elements.UserID.value);if(a=="")a=ConstantDefaultOutlineWidth}else if(_blnShowOutlineByDefault){a=new Date;var b=new Date;b.setTime(a.getTime()+31536E6);a=ConstantDefaultOutlineWidth;set_cookie("ShowOutline_"+document.frmParams.elements.UserID.value,true,b);_blnShowOutline="true"}else{a=new Date;
b=new Date;b.setTime(a.getTime()+31536E6);a=0;set_cookie("ShowOutline_"+document.frmParams.elements.UserID.value,false,b);_blnShowOutline="false"}}else a=0;return a}
function ChangeOutline(a){_blnIncludeOutline||(a="false");if(a=="true"){if(iPad){document.getElementById("ftc").style.display="";document.getElementById("tsep1").style.display="";document.getElementById("ftc").style.visibility="visible";document.getElementById("tsep1").style.visibility="visible";document.getElementById("ftc").style.width=_lngOutlineWidth+"px";$("#tsep1").removeClass("tsepCourseMainHidden");$("#tsep1").addClass("tsepCourseMain");document.getElementById("divOutline").style.width=_lngOutlineWidth+
"px";document.getElementById("tableOutline").style.width=_lngOutlineWidth+"px";document.getElementById("outlineframe").style.width=_lngOutlineWidth+"px"}else if(IsFirefox){document.getElementById("tsep1").style.display="";document.getElementById("ftc").style.visibility="visible";document.getElementById("ftc").style.width=_lngOutlineWidth+"px";$("#tsep1").removeClass("tsepCourseMainHidden");$("#tsep1").addClass("tsepCourseMain");document.getElementById("divOutline").style.width=_lngOutlineWidth+"px";
document.getElementById("tableOutline").style.width=_lngOutlineWidth+"px";document.getElementById("outlineframe").style.width=_lngOutlineWidth+"px"}else{document.getElementById("ftc").style.display="";document.getElementById("tsep1").style.display="";document.getElementById("divOutline").style.width=""+_lngOutlineWidth+"px";document.getElementById("tableOutline").style.width=""+_lngOutlineWidth+"px";document.getElementById("outlineframe").style.width=""+_lngOutlineWidth+"px"}document.getElementById("divOutlineHeader").style.width=
""+_lngOutlineWidth+"px";if(_blnIncludeOutline){iPad?$("#tvertical1").removeClass("tverticalWide_ios"):$("#tvertical1").removeClass("tverticalWide");$("#tvertical1").addClass("tvertical");getObjectById("divSplitter").style.left=""+(getOffsetLeft(getObjectById("tsep1"))-getObjectById("divSplitter").clientWidth+getObjectById("tsep1").offsetWidth)+"px";if(iPad){$("#divSplitter").removeClass("twistyClose_ios");$("#divSplitter").addClass("twistyOpen_ios")}else{$("#divSplitter").removeClass("twistyClose");
$("#divSplitter").addClass("twistyOpen")}getObjectById("divSplitter").title=StrClickToHideOutline}Resize();document.getElementById("cover").onmousemove=sepM;setTimeout("coverToSep()",500)}else{if(_blnIncludeOutline){$("#tvertical1").removeClass("tvertical");iPad?$("#tvertical1").addClass("tverticalWide_ios"):$("#tvertical1").addClass("tverticalWide");getObjectById("divSplitter").style.left="0px";if(iPad){$("#divSplitter").removeClass("twistyOpen_ios");$("#divSplitter").addClass("twistyClose_ios")}else{$("#divSplitter").removeClass("twistyOpen");
$("#divSplitter").addClass("twistyClose")}getObjectById("divSplitter").title=StrClickToShowOutline}if(iPad){document.getElementById("ftc").style.display="none";document.getElementById("tsep1").style.display="none";document.getElementById("ftc").style.visibility="hidden";document.getElementById("tsep1").style.visibility="hidden";document.getElementById("ftc").style.width="0px";$("#tsep1").removeClass("tsepCourseMain");$("#tsep1").addClass("tsepCourseMainHidden");document.getElementById("divOutline").style.width=
"0px";document.getElementById("tableOutline").style.width="0px";document.getElementById("outlineframe").style.width="0px";document.getElementById("divOutlineHeader").style.width="0px"}else if(IsFirefox){document.getElementById("tsep1").style.display="none";document.getElementById("ftc").style.visibility="hidden";document.getElementById("ftc").style.width="0px";$("#tsep1").removeClass("tsepCourseMain");$("#tsep1").addClass("tsepCourseMainHidden");document.getElementById("divOutline").style.width="0px";
document.getElementById("tableOutline").style.width="0px";document.getElementById("outlineframe").style.width="0px";document.getElementById("divOutlineHeader").style.width="0px"}else{document.getElementById("ftc").style.display="none";document.getElementById("tsep1").style.display="none"}setTimeout("coverToNone()",500);Resize()}if((new Date(new Date-OutlineTime)).getTime()>1E3||isIE4){OutlineTime=new Date;var b=new Date;b.setTime((new Date).getTime()+31536E6);set_cookie("ShowOutline_"+document.frmParams.elements.UserID.value,
a,b);_blnShowOutline=a}_blnOutlineDisplayed=a}
function StartPersonalFromLink(){document.frmParams.elements.StartPersonal.value=document.frmParams.elements.StartPersonal.value.toLowerCase()=="true"?"false":"true";getObjectById("contentframe").src="";document.location.href="CourseMain.aspx?LPathID="+document.frmParams.elements.LPathID.value+"&NodeID="+document.frmParams.elements.NodeID.value+"&UserID="+document.frmParams.elements.UserID.value+"&LangID="+document.frmParams.elements.LangID.value+"&StartMode="+document.frmParams.elements.StartMode.value+
"&GoBackTo="+document.frmParams.elements.GoBackTo.value+"&AllowPersonal="+document.frmParams.elements.AllowPersonal.value+"&StartPersonal="+document.frmParams.elements.StartPersonal.value+"&ChangePersonal=true&rnd="+(Math.round(Math.random()*1E5)+1)}
function StartPersonalWithGUID(a){document.frmParams.elements.StartPersonal.value=a;getObjectById("contentframe").src="";document.location.href="CourseMain.aspx?LPathID="+document.frmParams.elements.LPathID.value+"&NodeID="+document.frmParams.elements.NodeID.value+"&UserID="+document.frmParams.elements.UserID.value+"&LangID="+document.frmParams.elements.LangID.value+"&StartMode="+document.frmParams.elements.StartMode.value+"&GoBackTo="+document.frmParams.elements.GoBackTo.value+"&AllowPersonal="+
document.frmParams.elements.AllowPersonal.value+"&StartPersonal="+document.frmParams.elements.StartPersonal.value+"&ChangePersonal=true&rnd="+(Math.round(Math.random()*1E5)+1)}function GetStartPersonalValue(){return document.frmParams.elements.StartPersonal.value}var m_HasAssessmentCompleted=false;function ShowOutline(){ChangeOutline("true")}
function ShowPersonalLink(a){if(m_HasAssessmentCompleted==true&&document.getElementById("linkPersonal")!=null)if(a==1)document.getElementById("linkPersonal").style.display="";else document.getElementById("linkPersonal").style.display="none"}var LearningObjectID=-1,AssessType=0,NoteCount=0;function ViewNote(){AddBookmark(parseInt(document.frmParams.elements.UserID.value),LearningObjectID,NoteCount)}
function AskMentorFromLink(){AskMentor(parseInt(document.frmParams.elements.UserID.value),LearningObjectID,1)}function ProvideCommentFromLink(){AskMentor(parseInt(document.frmParams.elements.UserID.value),LearningObjectID,2)}
function UpdateNoteLink(a){if(a>0){document.getElementById("imgButNote").setAttribute("title",StrViewNote88);document.getElementById("imgButNote").setAttribute("alt",StrViewNote88);document.getElementById("imgButNote").src=StrViewNoteImage}else{document.getElementById("imgButNote").setAttribute("title",StrAddNote518);document.getElementById("imgButNote").setAttribute("alt",StrAddNote518);document.getElementById("imgButNote").src=StrAddNoteImage}}
function UpdateContentHeader(a,b,c){LearningObjectID=-1;AssessType=0;if(a!="I")if(a.length>4&&a.substring(0,4)=="PRE_"){AssessType=1;LearningObjectID=parseInt(a.substring(4))}else if(a.length>5&&a.substring(0,5)=="POST_"){AssessType=2;LearningObjectID=parseInt(a.substring(5))}else{AssessType=0;LearningObjectID=parseInt(a)}if(b!=undefined&&b!=null)m_HasAssessmentCompleted=b;if(document.frmParams.elements.AllowPersonal.value=="true"&&b==true){document.getElementById("tdPersonal").style.display="";if(document.frmParams.elements.StartPersonal.value.toLowerCase()==
"true")document.getElementById("linkPersonal").innerHTML=StrFullCourse681;else document.getElementById("linkPersonal").innerHTML=StrPersonalCourse680}else document.getElementById("tdPersonal").style.display="none";if(noteAvail==true&&AssessType==0&&LearningObjectID!=-1){document.getElementById("cellNote").style.display="";if(c>0){document.getElementById("imgButNote").setAttribute("title",StrViewNote88);document.getElementById("imgButNote").setAttribute("alt",StrViewNote88);document.getElementById("imgButNote").src=
StrViewNoteImage}else{document.getElementById("imgButNote").setAttribute("title",StrAddNote518);document.getElementById("imgButNote").setAttribute("alt",StrAddNote518);document.getElementById("imgButNote").src=StrAddNoteImage}}else document.getElementById("cellNote").style.display="none";if(feedbackAvail==true&&AssessType==0&&LearningObjectID!=-1)document.getElementById("cellFeedback").style.display="";else document.getElementById("cellFeedback").style.display="none";if(mentorAvail==true&&AssessType==
0&&LearningObjectID!=-1)document.getElementById("cellExpert").style.display="";else document.getElementById("cellExpert").style.display="none";document.getElementById("tdPersonal").style.display==""&&(document.getElementById("cellNote").style.display==""||document.getElementById("cellExpert"));document.getElementById("cellNote").style.display==""&&document.getElementById("cellExpert")}function MovePrevComp(){outline_MovePrev()}function MoveNextComp(){outline_MoveNext()}function UnloadMe(){}
function AskMentor(a,b,c){OpenNewQuestion(a,b,c)}
function OpenNewQuestion(a,b,c){ShowContent(false);a="../Mentoring/NewMentQuest.aspx?UserID="+document.frmParams.UserID.value+"&LangID="+document.frmParams.LangID.value+"&SiteID="+document.frmParams.SiteID.value+"&AuNodeId="+b+"&Section="+escape("")+"&Opener=CrNav&PathNode="+document.frmParams.NodeID.value+"&FeedbackType="+c;showDialog(a,-1,-1,510,400,true,96,"../Images/",false,closeImageURI);setParent(this);setOnCloseEvent("ShowContent(true);");return false}
function AddBookmark(a,b,c){if((new Date(new Date-NavTime)).getTime()>2E3){NavTime=new Date;NextWindow=Page_AddBookmark(a,b,c)}}function Page_AddBookmark(a,b,c){ShowContent(false);showDialog("../Notebook/Notes.aspx?UserID="+a+"&LearningObjectID="+b+"&Viewed="+c,-1,-1,510,340,true,96,"../Images/",false,closeImageURI);setParent(this);setOnCloseEvent("ShowContent(true);");return false}function imgOn(a){if(document.images)document[a].src=eval(a+"on.src")}
function imgOff(a){if(document.images)document[a].src=eval(a+"off.src")}function WinClose(){ExitKP("..")}function WebHelp(){DisplayHelp(document.frmParams.elements.LangID.value,HelpContextID,"../Help/")}
function NavBack(){switch(document.frmParams.GoBackTo.value){case "1":document.location.href="../Default.aspx";break;case "3":document.location.href="../LearningPaths/LPSelect.aspx?LPathID="+document.frmParams.elements.LPathID.value;break;case "4":document.location.href="../Notebook/Notebook.aspx";break;case "5":document.location.href="../Search/SearchMain.aspx";break;default:alert("Error")}}function NavHome(){NavToHome()}
function SetInactivityTimeout(){if(!blnIsContentExport)if(intMaxInactivityTime>0){clearTimeout(InactivityTimeoutID);InactivityTimeoutID=setTimeout("RedirectTimeout()",6E4*intMaxInactivityTime)}}function RedirectTimeout(){clearTimeout(InactivityTimeoutID);parent.location.replace("../Common/Timeout.aspx")}function getObjectById(a){return document.getElementById(a)}
var _ftcobj=null,_myTableObj=null,_header1DivObj=null,_treeContainerObj=null,_contentContainerObj=null,_outlineHeaderObj=null,_contentHeaderObj=null;function getOffsetLeft(a){var b=0;if(a.parentNode)b=getOffsetLeft(a.parentNode);return(a.offsetLeft?a.offsetLeft:0)+b}function getOffsetTop(a){var b=0;if(a.parentNode)b=getOffsetTop(a.parentNode);var c=0;if(a.offsetTop&&a.nodeName!="TR")c=a.offsetTop;return c+b}
function coverToSep(){if(!iPad)if(!_cover_dragged){var a=document.getElementById("sepdiv"),b=document.getElementById("cover");b.style.width=a.clientWidth+"px";b.style.height=a.clientHeight+"px";offsetLeft=getOffsetLeft(a);offsetTop=getOffsetTop(a);b.style.top=offsetTop+"px";b.style.left=offsetLeft+"px"}}function coverToFull(){if(!iPad){var a=document.getElementById("cover");a.style.top="0px";a.style.left="0px";a.style.width="100%";a.style.height="100%"}}
function coverToNone(){if(!iPad){var a=document.getElementById("cover");a.style.top="0px";a.style.left="0px";a.style.width="0px";a.style.height="0px"}}var _cover_dragged=false;function sepD(){if(!iPad){_cover_dragged=true;coverToFull();var a=document.getElementById("cover");a.setCapture&&a.setCapture()}}
function sepM(a){if(!iPad)if(!_cover_dragged)return;if(_ftcobj==null)_ftcobj=getObjectById("ftc");if(a==undefined)if(window.event!=undefined)a=window.event;else return;if(iPad){if(sepX!=a.pageX)sepPrevX=sepX;sepX=a.pageX}if(_blnOutlineDisplayed!="false"){var b=0;b=iPad?a.clientX-document.getElementById("divVertical1").offsetWidth+getObjectById("divSplitter").clientWidth:a.clientX-document.getElementById("divVertical1").offsetWidth-document.getElementById("tsep1").offsetWidth/2;if(b>0){_ftcobj.style.width=
""+b+"px";document.getElementById("outlineframe").style.width=""+b+"px";document.getElementById("divOutlineHeader").style.width=""+b+"px";document.getElementById("divOutline").style.width=""+b+"px";document.getElementById("tableOutline").style.width=""+b+"px";if(b+document.getElementById("tdContent").clientWidth+document.getElementById("tvertical1").offsetWidth*2+document.getElementById("tsep1").offsetWidth>browserWidth()){b=browserWidth()-document.getElementById("tdContent").clientWidth-document.getElementById("tvertical1").offsetWidth*
2-document.getElementById("tsep1").offsetWidth;_ftcobj.style.width=""+b+"px";document.getElementById("outlineframe").style.width=""+b+"px";document.getElementById("divOutlineHeader").style.width=""+b+"px";document.getElementById("divOutline").style.width=""+b+"px";document.getElementById("tableOutline").style.width=""+b+"px"}if(_blnIncludeOutline&&_blnOutlineDisplayed=="true")document.getElementById("divSplitter").style.left=""+(getOffsetLeft(getObjectById("tsep1"))-getObjectById("divSplitter").clientWidth+
getObjectById("tsep1").offsetWidth)+"px"}OutlineLoaded&&ResizePanels();setTimeout("_HResize()",1)}}
function sepU(){iPad||(_cover_dragged=false);if(iPad){var a=sepPrevX-sepX;if(a>30&&_blnOutlineDisplayed=="true"){ChangeOutline("false");return}else if(a<-30&&_blnOutlineDisplayed=="false"){ChangeOutline("true");return}}else{coverToSep();a=document.getElementById("cover");a.releaseCapture&&a.releaseCapture()}if(_ftcobj==null)_ftcobj=getObjectById("ftc");if(_ftcobj.offsetWidth<30)ChangeOutline("false");else{_lngOutlineWidth=_ftcobj.offsetWidth;a=new Date;a.setTime((new Date).getTime()+31536E6);set_cookie("OutlineWidth_"+
document.frmParams.elements.UserID.value,_lngOutlineWidth,a)}}function Resize(){document.getElementById("divBackgroundCover").display=="block"&&ShowBackgroundCover();setTimeout("_Resize()",1)}function _HResize(){coverToSep()}
function _Resize(){if(_blnIncludeOutline)if(_blnOutlineDisplayed=="true"){var a=document.getElementById("tableOutline").clientWidth;if(a+document.getElementById("tdContent").clientWidth+document.getElementById("tvertical1").offsetWidth*2+document.getElementById("tsep1").offsetWidth>browserWidth()){a=browserWidth()-document.getElementById("tdContent").clientWidth-document.getElementById("tvertical1").offsetWidth*2-document.getElementById("tsep1").offsetWidth;_ftcobj.style.width=""+a+"px";document.getElementById("outlineframe").style.width=
""+a+"px";document.getElementById("divOutlineHeader").style.width=""+a+"px";document.getElementById("divOutline").style.width=""+a+"px";document.getElementById("tableOutline").style.width=""+a+"px";document.getElementById("divSplitter").style.left=""+(getOffsetLeft(getObjectById("tsep1"))-getObjectById("divSplitter").clientWidth+getObjectById("tsep1").offsetWidth)+"px"}}else document.getElementById("divSplitter").style.left=0;a=0;if(iPad){if(document.body.clientHeight<225||document.body.clientWidth<
300)return false;a=document.body.clientHeight-document.getElementById("Td1").offsetHeight*2-_header1DivObj.clientHeight}else if(_contentContainerObj.clientHeight<800){if(document.body.clientHeight<330||document.body.clientWidth<300)return false;a=document.body.clientHeight-document.getElementById("Td1").offsetHeight*2-_header1DivObj.clientHeight}else a=upk.browserInfo.isIE8()?330-document.getElementById("Td1").offsetHeight*2-_header1DivObj.clientHeight+60:330-document.getElementById("Td1").offsetHeight*
2-_header1DivObj.clientHeight;if(a>=0)_myTableObj.style.height=""+a+"px";var b=a-_outlineHeaderObj.clientHeight;if(b>=0){_treeContainerObj.style.height=""+b+"px";document.getElementById("outlineframe").style.height=""+b+"px";OutlineLoaded&&ResizePanels()}a=a-_contentHeaderObj.clientHeight-document.getElementById("Td1").offsetHeight;if(a>=0){_contentContainerObj.style.height=""+a+"px";document.getElementById("divContentFrame").style.height=""+a+"px"}if(_blnIncludeOutline)getObjectById("divSplitter").style.top=
""+(getOffsetTop(getObjectById("tvertical1"))+getObjectById("tvertical1").offsetHeight/2-getObjectById("divSplitter").offsetHeight/2)+"px";_HResize()}function ChangeCursor(a,b){a.style.cursor=b}
function disableHeaderLink(a,b){if(b){var c=a.getAttribute("href");c&&c!=""&&c!=null&&a.setAttribute("href_bak",c);a.removeAttribute("href");a.className="NavHypertextLightDisabled"}else{a.attributes.href_bak!=null?a.setAttribute("href",a.attributes.href_bak.nodeValue):a.setAttribute("href","");a.className="NavHypertextLight"}}
function DisplayNavButton(a,b){if(b==false)switch(a){case 1:var c=document.getElementById("imgButPrev"),d=document.getElementById("lnkPreviousButton");if(d.className=="NavHypertextLight"){disableHeaderLink(d,!b);c.src=imgPrevPreloadDisable.src;c.onclick=function(){return false}}break;case 2:c=document.getElementById("imgButNext");d=document.getElementById("lnkNextButton");if(d.className=="NavHypertextLight"){disableHeaderLink(d,!b);c.src=imgNextPreloadDisable.src;c.onclick=function(){return false}}}else switch(a){case 1:c=
document.getElementById("imgButPrev");d=document.getElementById("lnkPreviousButton");if(d.className=="NavHypertextLightDisabled"){disableHeaderLink(d,!b);c.src=imgPrevPreload.src;c.onclick=function(){MovePrevComp();return false}}break;case 2:c=document.getElementById("imgButNext");d=document.getElementById("lnkNextButton");if(d.className=="NavHypertextLightDisabled"){disableHeaderLink(d,!b);c.src=imgNextPreload.src;c.onclick=function(){MoveNextComp();return false}}}}
function UpdateOutlineHeader(a,b){document.getElementById("lblOutline").innerHTML=a;document.getElementById("lblStatus").innerHTML=b;document.getElementById("lblStatus").style.display=""}var m_AnswerFunction;
function CustomConfirm(a,b,c,d,e,g){document.getElementById("lblWindowTitle").innerHTML=a;document.getElementById("lblConfirmText").innerHTML=b;a=document.getElementById("divContentArea").getElementsByTagName("input");if(c!=""){a[0].value=c;a[0].style.display=""}else a[0].style.display="none";if(d!=""){a[1].value=d;a[1].style.display=""}else a[1].style.display="none";if(e!=""){a[2].value=e;a[2].style.display=""}else a[2].style.display="none";m_AnswerFunction=g;ShowBackgroundCover();c=document.getElementById("divWindow");
d=document.body.clientWidth/2-c.offsetWidth/2;c.style.top=document.body.clientHeight/2-c.offsetHeight/2+"px";c.style.left=d+"px";c.style.display="";c.style.visibility="visible"}function answer(a){document.getElementById("divWindow").style.display="none";HideBackgroundCover();m_AnswerFunction(a)}var m_current_object,m_ObjectX,m_ObjectY,m_StartX,m_StartY,m_Width,m_Height;
function begin_event(a,b){if(m_current_object==null){var c=window.event?window.event:b,d=document.getElementById("divWindow"),e=document.getElementById("divContentArea");m_current_object=a;if(c.pageX||c.pageY){m_ObjectX=c.pageX;m_ObjectY=c.pageY}else{m_ObjectX=c.clientX;m_ObjectY=c.clientY}m_StartX=parseInt(d.offsetLeft);m_StartY=parseInt(d.offsetTop);m_Width=parseInt(d.offsetWidth);m_Height=parseInt(e.offsetHeight);e.style.visibility="hidden";document.onmousemove=drag_event;document.onmouseup=end_event}return false}
function drag_event(a){if(m_current_object!=null){var b=window.event||a;if(b.pageX||b.pageY){a=b.pageX-m_ObjectX;b=b.pageY-m_ObjectY}else{a=b.clientX-m_ObjectX;b=b.clientY-m_ObjectY}m_current_object.className=="divTitleBar"&&MoveBy(a,b)}return false}function MoveBy(a,b){document.getElementById("divWindow").style.left=Math.max(m_StartX+a,0)+"px";document.getElementById("divWindow").style.top=Math.max(m_StartY+b,0)+"px"}
function end_event(){document.getElementById("divContentArea").style.visibility="visible";m_current_object=null;document.onmousemove=null;document.onmouseup=null}function ShowBackgroundCover(){var a=document.getElementById("divBackgroundCover");a.style.left=0;a.style.top=0;a.style.width="100%";a.style.height="100%";a.style.visibility="visible";a.style.display="block"}
function HideBackgroundCover(){var a=document.getElementById("divBackgroundCover");a.style.visibility="hidden";a.style.display="none"}function browserWidth(){if(self.innerWidth)return self.innerWidth;else if(document.documentElement&&document.documentElement.clientHeight)return document.documentElement.clientWidth;else if(document.body)return document.body.clientWidth;return 0}function detectIPadOrientation(){_blnIncludeOutline?ChangeOutline("true"):ChangeOutline("false")}function Swipe(){}
Swipe.prototype.Init=function(a){this.dy=this.dx=this.y=this.x=0;this.width=a;this.multi=false};Swipe.prototype.Add=function(a,b){if(this.x==0&&this.y==0){this.x=this.dx=a;this.y=this.dy=b}else{this.dx=a;this.dy=b}};Swipe.prototype.IsNotZoomed=function(){if(window.innerWidth>this.width)return true;return Math.abs(window.innerWidth-this.width)<5};Swipe.prototype.DetectedMulti=function(){this.multi=true};Swipe.prototype.IsMulti=function(){return this.multi};
Swipe.prototype.Result=function(){return""+(this.dx-this.x)+" "+(this.dy-this.y)};Swipe.prototype.GetX=function(){return this.dx-this.x};Swipe.prototype.GetY=function(){return this.dy-this.y};Swipe.prototype.GetPoint=function(){return""+this.dx+","+this.dy};function Splitter_onclick(){_blnOutlineDisplayed=="true"?ChangeOutline("false"):ChangeOutline("true")}function virticalline_onclick(){iPad&&_blnOutlineDisplayed=="false"&&ChangeOutline("true")}
function ShowContent(a){if(a)document.getElementById("divContentFrame").style.visibility="visible";else document.getElementById("divContentFrame").style.visibility="hidden"};var dlg_parent,dialogh_ref,device_dpi,dialog2_html,modal_dialog,dlg_width,dlg_height,dlg_autosizeheight=false,callback_end="",isopened=false,dlg_context="",grayPosition,overflowValue="";function setParent(a){dlg_parent=a}function Click1(){closeDialog();$("#graydiv").remove()}function getDPI(){return device_dpi}function setWidth(a,b){$(a).css("width",b)}function setHeight(a,b){$(a).css("height",b)}
function setPadding(a,b,c){b="<div style='padding:"+b+"px'";if(c&&c!="")b+=" class='"+c+"'";b+=">"+a+"</div>";return b}function getContentSize(a){var b={width:0,height:0};a=$("<div style='display:visible;position:absolute;top:0px;left:0px;' id='04A98DB973UPK'>"+a+"</div>");$("body").append(a);b.width=$("#04A98DB973UPK").outerWidth(true);b.height=$("#04A98DB973UPK").outerHeight(true);$("#04A98DB973UPK").remove();return b}
function showDialog3(a,b,c,d,e,g,f,i,j){showDialog2(a,b,c,d,e,g,f,i);$("body").append("<div id='04A98DB974UPK'>"+j+"</div>")}function showDialog2(a,b,c,d,e,g,f,i){dlg_autosizeheight=e==-1?true:false;dialog2_html=a;showDialog("",b,c,d,e,g,f,"",i)}
(function(a){a.fn.drags=function(b){b=a.extend({handle:"",cursor:"move"},b);var c=a("<div>",{id:"ehandler",css:{position:"absolute",top:0,left:0,right:0,bottom:0,display:"none",cursor:b.cursor,"z-index":999,"background-color":"red",opacity:"0",filter:"alpha(opacity=0)"}}).appendTo(document.body);return this.addClass("draggable").each(function(){$drag=a(this);(b.handle===""?$drag:$drag.find(b.handle)).addClass("active-handle").on("mousedown",function(d){if(a(d.target).is(a(this))){$drag.css("cursor",
b.cursor);d.preventDefault();$drag.css("z-index");var e=$drag.outerHeight(),g=$drag.outerWidth(),f=$drag.offset().top+e-d.pageY,i=$drag.offset().left+g-d.pageX;c.show().on("mousemove",function(j){j.preventDefault();y=j.pageY+f-e;x=j.pageX+i-g;if(y<0)y=0;if(x<0)x=0;a(".draggable").offset({top:y,left:x})}).add(document).on("mouseup",function(j){$drag.css("cursor","default");j.preventDefault();a(this).off("mousemove mouseup");c.hide()})}})})}})(jQuery);
function showDialog(a,b,c,d,e,g,f,i,j,l){isopened=true;f=96;if(b!=-1)b=PtToPx(b,f);if(c!=-1)c=PtToPx(c,f);d=PtToPx(d,f);e=PtToPx(e,f);dlg_width=d;dlg_height=e;device_dpi=f;dialogh_ref=a;modal_dialog=g;if(b==-1||c==-1){c=b=0;if(window.innerWidth){b=window.innerWidth;c=window.innerHeight}else if(document.documentElement){b=document.documentElement.scrollWidth;c=document.documentElement.scrollHeight}b=Math.floor(b/2-d/2+$(document).scrollLeft());c=Math.floor(c/2-e/2+$(document).scrollTop());if(b<0)b=
100;if(c<0)c=100}if(j)j=dialogh_ref;if(document.body.scrollHeight<e)c=0;if(g){if(upk.browserInfo.isIEQuirks()){grayPosition="absolute";overflowValue=$(document.body).css("overflow");overflowValue==="auto"&&$(document.body).css("overflow","");document.body.scroll="no"}else grayPosition="fixed";$(document.body).append('<div id="graydiv" scrolling="no" class="pointerdiv" style="position:'+grayPosition+';display:none;z-index: 99;top:0;left:0;bottom:0;right:0;"></div>')}else $(document.body).append('<div id="graydiv" scrolling="yes" class="pointerdiv2" style="display:none;z-index: 99;" onclick="if (dlg_parent!= undefined && dlg_parent!= null) {dlg_parent.Click1();} else {parent.Click1();}"></div>');
$("#graydiv").on("touchmove",function(){return false});$("#graydiv").show();style="left:"+b+"px; top:"+c+"px; width: "+d+"px; height: "+e+"px;";wwpx=d-60;hhpx=e-60;if(upk.browserInfo.isIEQuirks()&&upk.browserInfo.isIE9()){wwpx-=20;hhpx-=20}innerstyle="width: "+wwpx+"px; height: "+hhpx+"px;";j="iossafefordesktop";if(IsTouchDevice())j="iossafe";if(g){$(document.body).append('<div class="desktopDialog" id="dialog" style="'+style+'"><div id="closebtn" onclick="if (dlg_parent!= undefined && dlg_parent!= null) {dlg_parent.Click1();} else {parent.Click1();}"><img id="closeimg" class="close_qualifier" src="'+
l+'" alt="" width="16" /></div><div class="'+j+'" style="'+innerstyle+'"><iframe id="dialogBody" frameborder="0" scrolling="no" src="'+a+'" style="width: 100%; height: 100%;margin:0px; padding:0px; position: absolute;top: 0px; left: 0px; background-color: white;"></iframe></div></div>');$("#dialog").drags();$("#dialog").on("touchmove",function(){return false})}else{innerstyle="width: "+d+"px; height: "+e+"px;";j="../html/dialog2.html";$(document.body).append('<div class="noborderDialog" id="dialog" style="'+
style+'"><div id="dialogBodyDiv" class="noBorderDialogDesktop" style="'+innerstyle+'"><iframe id="dialogBody" frameborder="0" scrolling="no" src="'+j+'" style="width: 100%; height: 100%;margin:0px; padding:0px; position: absolute;top: 0px; left: 0px; background-color: white;"></iframe></div></div>')}dlg_context!=""&&ctxHelper.SetContext(dlg_context)}function isOpenDialog(){return isopened}function removeDiv(a){$(a).remove()}function appendDiv(a){$(document.body).append(a)}
function closeDialog(){$("#04A98DB974UPK").remove();$("#graydiv").remove();$("#dialog").remove();$("#ehandler").remove();if(dlg_context!=""){ctxHelper.SetPrevContext();dlg_context=""}if(upk.browserInfo.isIEQuirks()){if(overflowValue=="auto"){$(document.body).css("overflow",overflowValue);overflowValue=""}document.body.scroll="auto"}isopened=false;if(dlg_parent)callback_end&&dlg_parent.eval(callback_end);else callback_end&&eval(callback_end)}function setOnCloseEvent(a){callback_end=a}
function getOnCloseEvent(){return callback_end}function getDialog2Content(){return dialog2_html}function setDlgCtx(a){dlg_context=a};var NAV_REQUEST_START=1,NAV_REQUEST_RESUMEALL=2,NAV_REQUEST_CONTINUE=3,NAV_REQUEST_PREVIOUS=4,NAV_REQUEST_FORWARD=5,NAV_REQUEST_BACKWORD=6,NAV_REQUEST_CHOICE=7,NAV_REQUEST_EXIT=8,NAV_REQUEST_EXITALL=9,NAV_REQUEST_SUSPENDALL=10,NAV_REQUEST_ABANDON=11,NAV_REQUEST_ABANDONALL=12,LastItem=0,AllowMove=false,m_HighLightItem=null,m_NavRequest,m_ChoiceTargetNodeID,_pnlOutlineHeader=null,_pnlPreassess=null,_pnlPostassess=null,_pnlCourse=null,_pnlCourseHeader=null,_pnlCourseInfo=null,_pnlPreassessHeader=null,
_pnlPreassessInfo=null,_pnlPostassessHeader=null,_pnlPostassessInfo=null,_pnlTree=null;
function Init_Outline(){SetInactivityTimeout();if(_pnlPreassess==null)_pnlPreassess=document.getElementById("pnlPreassess");if(_pnlPostassess==null)_pnlPostassess=document.getElementById("pnlPostassess");if(_pnlCourse==null)_pnlCourse=document.getElementById("pnlCourse");if(_pnlCourseHeader==null)_pnlCourseHeader=document.getElementById("dHeader"+m_Course.CourseLearningObjectID);if(_pnlCourseInfo==null)_pnlCourseInfo=document.getElementById("dInfo"+m_Course.CourseLearningObjectID);if(_pnlPreassessHeader==
null&&m_Course.Preassess!=null)_pnlPreassessHeader=document.getElementById("dHeader"+m_Course.Preassess.NodeID);if(_pnlPreassessInfo==null&&m_Course.Preassess!=null)_pnlPreassessInfo=document.getElementById("dInfo"+m_Course.Preassess.NodeID);if(_pnlPostassessHeader==null&&m_Course.Postassess!=null)_pnlPostassessHeader=document.getElementById("dHeader"+m_Course.Postassess.NodeID);if(_pnlPostassessInfo==null&&m_Course.Postassess!=null)_pnlPostassessInfo=document.getElementById("dInfo"+m_Course.Postassess.NodeID);
if(_pnlTree==null)_pnlTree=document.getElementById("PanelTree");RepopulatePanels();if(m_Course.DeliveryNodeID=="I"&&m_Course.Preassess==null&&m_Course.Postassess==null)outline_MoveNext();else{GotoDeliveryLearningObject(m_Course.DeliveryNodeID,"");LaunchContent(m_Course.DeliveryNodeID)}OutlineLoaded=true}
function RepopulatePanels(){if(m_Course.Preassess!=null){_pnlPreassess.style.display="";PupulatePanel(m_Course.Preassess,1)}else _pnlPreassess.style.display="none";if(m_Course.Postassess!=null){_pnlPostassess.style.display="";PupulatePanel(m_Course.Postassess,2)}else _pnlPostassess.style.display="none";if(document.frmParams.elements.NodeID.value!="0"&&m_Course.HasCourse||document.frmParams.elements.NodeID.value=="0"){_pnlCourse.style.display="";m_Course.Preassess!=null||m_Course.Postassess!=null?
PupulatePanel(m_Course.LOArray[LOXref["K_"+m_Course.CourseLearningObjectID]],0):setTimeout("UpdateOutlineHeader(m_str102,  '("+GetLOStatus(m_Course.LOArray[LOXref["K_"+m_Course.CourseLearningObjectID]],0)+")')",1)}else if(_pnlCourse!=null)_pnlCourse.style.display="none";ResizePanels()}
function PupulatePanel(a,b){if(b==1||b==2)if(a.Enabled==0){document.getElementById("imgPlay"+a.NodeID).style.display="none";if(b==1&&m_Course.DeliveryNodeID.length>4&&m_Course.DeliveryNodeID.substring(0,4)=="PRE_")document.getElementById("link"+a.NodeID).className="OutlinePanelHeaderTextHighlightDisabled";else if(b==2&&m_Course.DeliveryNodeID.length>5&&m_Course.DeliveryNodeID.substring(0,5)=="POST_")document.getElementById("link"+a.NodeID).className="OutlinePanelHeaderTextHighlightDisabled";else document.getElementById("link"+
a.NodeID).className="OutlinePanelHeaderTextDisabled"}else{document.getElementById("imgPlay"+a.NodeID).style.display="";if(!(b==1&&m_Course.DeliveryNodeID.length>4&&m_Course.DeliveryNodeID.substring(0,4)=="PRE_"))if(!(b==2&&m_Course.DeliveryNodeID.length>5&&m_Course.DeliveryNodeID.substring(0,5)=="POST_"))document.getElementById("link"+a.NodeID).className="OutlinePanelHeaderText"}else if(a.Enabled==0){document.getElementById("lbl"+a.NodeID).className="OutlinePanelHeaderTextDisabled";_pnlTree.style.display=
"none"}else{if(m_Course.DeliveryNodeID==""||m_Course.DeliveryNodeID=="I"||m_Course.DeliveryNodeID.length>4&&m_Course.DeliveryNodeID.substring(0,4)=="PRE_"||m_Course.DeliveryNodeID.length>5&&m_Course.DeliveryNodeID.substring(0,5)=="POST_")document.getElementById("lbl"+a.NodeID).className="OutlinePanelHeaderText";else document.getElementById("lbl"+a.NodeID).className="OutlinePanelHeaderTextHighlight";_pnlTree.style.display=""}var c=GetLOStatus(a,b);document.getElementById("status"+a.NodeID).innerHTML=
" ("+c+")";var d=c="";switch(b){case 1:if(m_Course.PreassessRequired==true&&m_Course.Preassess.CompletionStatus!=1){c=m_str699;d=m_str697}else if(m_Course.Preassess.CompletionStatus==1){c=m_str700;d=m_str698}break;case 0:if(m_Course.Preassess!=null&&m_Course.PreassessRequired==true&&m_Course.Preassess.CompletionStatus!=1){c=m_str701;d=m_str698}else if(m_Course!=null&&m_Course.SubjectRequired==true&&m_Course.CompletionStatus!=1){c=m_str702;d=m_str697}break;case 2:if(m_Course.Postassess.Enabled==false)if(m_Course.Preassess!=
null&&m_Course.PreassessRequired==true&&m_Course.Preassess.CompletionStatus!=1&&m_Course!=null&&m_Course.SubjectRequired==true&&m_Course.CompletionStatus!=1){c=m_str703;d=m_str698}else if(m_Course.Preassess!=null&&m_Course.PreassessRequired==true&&m_Course.Preassess.CompletionStatus!=1){c=m_str704;d=m_str698}else{if(m_Course!=null&&m_Course.SubjectRequired==true&&m_Course.CompletionStatus!=1){c=m_str705;d=m_str698}}else if(m_Course.PostassessRequired==true&&m_Course!=null&&m_Course.CompletionStatus!=
1){c=m_str706;d=m_str697}}document.getElementById("lblLongInfo"+a.NodeID).innerHTML=c+"&nbsp;";document.getElementById("lblShortInfo"+a.NodeID).innerHTML=d+"&nbsp;";if(c=="")document.getElementById("dInfo"+a.NodeID).style.display="none";else document.getElementById("dInfo"+a.NodeID).style.display="";if(b==1&&a.CompletionStatus==1)get_cookie("PreassessCompletionCollapse_"+document.frmParams.UserID.value)=="1"?DisplayInfo(a.NodeID,1):DisplayInfo(a.NodeID,0)}
function GetLOStatus(a,b){var c="";switch(a.CompletionStatus){case 1:c=b==1||b==2?m_str329+": "+Math.round(a.ScoreScaled*100)+"%":m_str687;break;case 2:c=b==1||b==2?m_str708:a.ProgressMeasure==null||a.ProgressMeasure==undefined?m_str708+" 0%":m_str708+" "+Math.round(a.ProgressMeasure*100)+"%";break;case 3:case 4:c=m_str689}return c}
function ResizePanels(){if(!(_treeContainerObj==undefined||_treeContainerObj==null)){var a=_treeContainerObj.clientHeight;document.getElementById("outlineframe").style.height=""+a+"px";if(m_Course!=null&&m_Course.Preassess==null&&m_Course.Postassess==null)_pnlTree.style.height=a+"px";else if(m_Course!=null)if(_pnlTree.style.display==""){var b=0;var c=b=0;if(m_Course.Postassess!=null){c=document.getElementById("dInfo"+m_Course.Postassess.NodeID).style.display=="none"?document.getElementById("dHeader"+
m_Course.Postassess.NodeID).offsetHeight:document.getElementById("dHeader"+m_Course.Postassess.NodeID).offsetHeight+document.getElementById("dInfo"+m_Course.Postassess.NodeID).offsetHeight;_pnlPostassess.style.height=c+"px"}if(m_Course.Preassess!=null){b=document.getElementById("dInfo"+m_Course.Preassess.NodeID).style.display=="none"?document.getElementById("dHeader"+m_Course.Preassess.NodeID).offsetHeight:document.getElementById("dHeader"+m_Course.Preassess.NodeID).offsetHeight+document.getElementById("dInfo"+
m_Course.Preassess.NodeID).offsetHeight;_pnlPreassess.style.top="0px";_pnlPreassess.style.height=b+"px";_pnlCourse.style.top=b+"px"}_pnlPostassess.style.top=a-c+"px";var d=a-b-c;_pnlCourse.style.height=d>0?d+"px":"0px";d=0;if(_pnlCourseHeader!=null)d=_pnlCourseHeader.offsetHeight;var e=0;if(_pnlCourseInfo!=null)e=_pnlCourseInfo.style.display=="none"?0:_pnlCourseInfo.offsetHeight;a=a-b-c-d-e;_pnlTree.style.height=a>0?a+"px":"0px"}else{b=a-_pnlPreassess.offsetHeight-_pnlCourse.offsetHeight;_pnlPostassess.style.top=
b+"px"}else{b=a-_pnlPreassess.offsetHeight-_pnlCourse.offsetHeight;_pnlPostassess.style.top=b+"px"}}}
function ClearHighlightItem(){if(m_HighLightItem!=null){var a;a=m_HighLightItem.id.length>7&&m_HighLightItem.id.substring(0,7)=="dHeader"?m_HighLightItem.id.substring(7):m_HighLightItem.id.substring(1);var b=document.getElementById("link"+a);if(a.length>4&&a.substring(0,4)=="PRE_"){if(m_Course.Preassess.Enabled==0){m_HighLightItem.className="OutlinePanelHeader";b.className="OutlinePanelHeaderTextDisabled"}else{m_HighLightItem.className="OutlinePanelHeader";b.className="OutlinePanelHeaderText"}b=document.getElementById("status"+
a);b.className="OutlinePanelInfoText";b=document.getElementById("lblLongInfo"+a);b.className="OutlinePanelInfoText";a=document.getElementById("lblShortInfo"+a);a.className="OutlinePanelInfoText"}else if(a.length>5&&a.substring(0,5)=="POST_"){m_HighLightItem.className="OutlinePanelHeader";b.className="OutlinePanelHeaderText";b=document.getElementById("status"+a);b.className="OutlinePanelInfoText";b=document.getElementById("lblLongInfo"+a);b.className="OutlinePanelInfoText";a=document.getElementById("lblShortInfo"+
a);a.className="OutlinePanelInfoText"}else b.className="Node";m_HighLightItem=null}}function ChangeNavButtons(a){a=="I"?DisplayNavButton(1,false):DisplayNavButton(1,true);DisplayNavButton(2,true)}
function GotoDeliveryLearningObject(a,b){ChangeNavButtons(a);ClearHighlightItem();if(a=="")m_HighLightItem=null;else if(a=="I"){m_HighLightItem=null;window.status="Instructions"}else{var c=null,d=null;d=d=d=null;if(a.length>4&&a.substring(0,4)=="PRE_"||a.length>5&&a.substring(0,5)=="POST_"){d=document.getElementById("dHeader"+m_Course.CourseLearningObjectID);document.getElementById("lbl"+m_Course.CourseLearningObjectID);if(d!=null){d.className="OutlinePanelHeader";d=document.getElementById("lbl"+
m_Course.CourseLearningObjectID);if(m_Course!=null)d.className=m_Course.LOArray[LOXref["K_"+m_Course.CourseLearningObjectID]].Enabled==1?"OutlinePanelHeaderText":"OutlinePanelHeaderTextDisabled";d=document.getElementById("status"+m_Course.CourseLearningObjectID);d.className="OutlinePanelInfoText"}c=document.getElementById("dHeader"+a);c.className="OutlinePanelHeaderHighlight";d=document.getElementById("link"+a);d.className="OutlinePanelHeaderTextHighlight";document.getElementById("status"+a).className=
"OutlinePanelInfoTextHighlight";m_HighLightItem=c}else{d=document.getElementById("dHeader"+m_Course.CourseLearningObjectID);if(d!=null){d.className="OutlinePanelHeaderHighlight";d=document.getElementById("lbl"+m_Course.CourseLearningObjectID);d.className="OutlinePanelHeaderTextHighlight";d=document.getElementById("status"+m_Course.CourseLearningObjectID);d.className="OutlinePanelInfoTextHighlight"}c=document.getElementById("d"+a);for(document.getElementById("link"+a);c.style.display=="none";){c.parentNode.style.display=
"";SetPlusMinus(document.getElementById("imgOutl"+c.parentNode.id.substr(4)),document.getElementById("pic"+c.parentNode.id.substr(4)),false);c=c.parentNode.previousSibling}d=document.getElementById("link"+c.id.substr(1));d.className="Node_Highlight";for(m_HighLightItem=c;c.id!="d"+m_Course.CourseLearningObjectID;){c.parentNode.style.display="";SetPlusMinus(document.getElementById("imgOutl"+c.parentNode.id.substr(4)),document.getElementById("pic"+c.parentNode.id.substr(4)),false);c=c.parentNode.previousSibling}c=
navigator.appName.indexOf("Microsoft")!=-1?true:false;if(b==NAV_REQUEST_PREVIOUS)if(c){if(document.getElementById("PanelTree").scrollTop>m_HighLightItem.offsetTop)document.getElementById("PanelTree").scrollTop=m_HighLightItem.offsetTop}else{if(document.getElementById("PanelTree").scrollTop>m_HighLightItem.offsetTop-document.getElementById("PanelTree").offsetTop)document.getElementById("PanelTree").scrollTop=m_HighLightItem.offsetTop-document.getElementById("PanelTree").offsetTop}else if(b==NAV_REQUEST_CONTINUE)if(c){if(document.getElementById("PanelTree").scrollTop<
m_HighLightItem.offsetTop+40-document.getElementById("PanelTree").offsetHeight)document.getElementById("PanelTree").scrollTop=m_HighLightItem.offsetTop+40-document.getElementById("PanelTree").offsetHeight}else if(document.getElementById("PanelTree").scrollTop<m_HighLightItem.offsetTop-document.getElementById("PanelTree").offsetTop+40-document.getElementById("PanelTree").offsetHeight)document.getElementById("PanelTree").scrollTop=m_HighLightItem.offsetTop-document.getElementById("PanelTree").offsetTop+
40-document.getElementById("PanelTree").offsetHeight}setTimeout("GoToItem('"+a+"')",100);if(m_HighLightItem!=null)window.status=d.innerHTML}}
function SetPlusMinus(a,b,c){var d=a.name;if(!(d.toLowerCase().substr(d.length-2)=="_r"||d.toLowerCase().substr(d.length-2)=="_l"||d.toLowerCase().substr(d.length-2)=="_f"||d.toLowerCase().substr(d.length-2)=="_m")){if(c==true){a.name=d.substr(0,d.length-1)+"c";b.src=closedSection_img.src}else{a.name=d.substr(0,d.length-1)+"o";b.src=openSection_img.src}a.src=expandimages[a.name]}}
function Outline_Select_ByUser(a){if(m_Course.PlayMode==2)if(!m_Course.IsPrevOrNextItem(a))return;Outline_Select(a,false)}
function Outline_Select(a,b){if(!(b!=undefined&&b==true))if(m_Course.DeliveryNodeID==a)return;if(document.getElementById("link"+a).className=="Node_Disabled"||document.getElementById("link"+a).className=="OutlinePanelHeaderTextDisabled"||document.getElementById("link"+a).className=="OutlinePanelHeaderTextHighlightDisabled")SetInactivityTimeout();else{m_NavRequest=NAV_REQUEST_CHOICE;m_ChoiceTargetNodeID=a;if(m_HighLightItem==null){m_Course.DeliveryNodeID=m_Course.FindChoiceItem(m_ChoiceTargetNodeID);
GotoDeliveryLearningObject(m_Course.DeliveryNodeID,"");LaunchContent(m_Course.DeliveryNodeID)}else{var c=m_Course.FindChoiceItem(m_ChoiceTargetNodeID);if(c!=m_Course.DeliveryNodeID){m_Course.DeliveryNodeID=c;GotoDeliveryLearningObject(m_Course.DeliveryNodeID,"");LaunchContent(m_Course.DeliveryNodeID)}}}}function RefreshOutline(){GetUpdatedResults(false,NAV_REQUEST_CHOICE,m_Course.DeliveryNodeID)}
function RefreshOutline2(a,b){SetInactivityTimeout();m_Course.OverallRollupProcess(m_Course.DeliveryNodeID,a,b);m_Course.StartSequencingProcess(m_Course.DeliveryNodeID,a,b);UpdateOutline()}
function GetUpdatedResults(a,b,c){SetInactivityTimeout();OutlineLoaded=false;var d=m_Course.DeliveryNodeID;if(d=="I")d="";PageMethods.GetUpdatedResults(document.frmParams.UserID.value,document.frmParams.NodeID.value,m_Course.CourseLearningObjectID,document.frmParams.StartPersonal.value,d,b,c,m_Course.DeliveryNodeResultDate,a,GetUpdatedResultsOnSucceeded,GetUpdatedResultsOnFailed,b)}
function GetUpdatedResultsOnSucceeded(a,b){var c=GetLearningObjectArray(a);UpdateOutline();if(c=="1"){GotoDeliveryLearningObject(m_Course.DeliveryNodeID,b);LaunchContent(m_Course.DeliveryNodeID)}OutlineLoaded=true}function GetUpdatedResultsOnFailed(){OutlineLoaded=true}function LaunchCurrentContent(){GotoDeliveryLearningObject(m_Course.DeliveryNodeID,"");LaunchContent(m_Course.DeliveryNodeID);OutlineLoaded=true}function GUIDPair(a,b){this.NodeID=a;this.GUID=b}
function GetStatus(a,b){var c="";switch(a){case 1:switch(b){case 1:c=m_str369;break;case 2:c=m_str370;break;default:c=m_str687}break;case 2:c=m_str708;break;default:c=m_str689}return c}
function GetLearningObjectResult(a,b){a.Visible=parseInt(b[1]);a.Skip=parseInt(b[2]);a.HiddenFromChoice=parseInt(b[3]);a.Enabled=parseInt(b[4]);a.CompletionStatus=parseInt(b[5]);a.SuccessStatus=parseInt(b[6]);a.ScoreScaled=b[7]=="null"?null:parseFloat(b[7]);a.ProgressMeasure=b[8]=="null"?null:parseFloat(b[8]);a.IsPersonalContentItem=parseInt(b[9]);a.PersonalOBJSuccessStatus=parseInt(b[10]);a.VisibleChildrenCount=parseInt(b[11]);a.IsLastChild=parseInt(b[12])}
function GetLearningObjectArray(a){var b=false,c=[],d=false;c=a.toString().split(";");if(c[0].length!=0){a=c[0].split(",");if(a.length>0){if(a[0]!=""){m_Course.DeliveryNodeID=a[0];m_Course.DeliveryNodeResultDate=a[1];m_Course.HideGUIPrev=a[2];m_Course.HideGUINext=a[3];m_Course.PrevLONodeIDs=a[4];m_Course.NextLONodeIDs=a[5];d=eval(a[6]);b=eval(a[7])}else{d=eval(a[6]);b=eval(a[7]);if(b==true)if(m_NavRequest==NAV_REQUEST_CONTINUE)if(m_Course.DeliveryNodeID.length>4&&m_Course.DeliveryNodeID.substring(0,
4)=="PRE_"&&m_Course==null&&m_Course.Postassess==null)NavBack();else confirm(strEndOfOutlineMsg)&&NavBack()}if(m_Course.AllowPersonal==true&&m_Course.HasAssessmentCompleted==false&&d==true)m_Course.HasAssessmentCompleted=d}}for(d=1;d<c.length;d++)if(c[d].length!=0){a=c[d].split(",");if(a.length>0)if(a[0].length>4&&a[0].substring(0,4)=="PRE_")GetLearningObjectResult(m_Course.Preassess,a);else a[0].length>5&&a[0].substring(0,5)=="POST_"?GetLearningObjectResult(m_Course.Postassess,a):GetLearningObjectResult(m_Course.LOArray[LOXref["K_"+
a[0]]],a)}return b}
function UpdateOutline(){RepopulatePanels();for(var a=0;a<m_Course.LOArray.length;a++){var b=document.getElementById("d"+m_Course.LOArray[a].NodeID),c=document.getElementById("item"+m_Course.LOArray[a].NodeID);document.getElementById("pic"+m_Course.LOArray[a].NodeID);var d=document.getElementById("picStatus"+m_Course.LOArray[a].NodeID),e=document.getElementById("link"+m_Course.LOArray[a].NodeID);if(b!=null&&b!=undefined){if(m_Course.LOArray[a].Visible==1&&m_Course.LOArray[a].HiddenFromChoice==0){if(b.style.display!=
""){b.style.display="";c.style.display="";SetPlusMinus(document.getElementById("imgOutl"+c.id.substr(4)),document.getElementById("pic"+c.id.substr(4)),false)}}else{b.style.display="none";c.style.display="none";SetPlusMinus(document.getElementById("imgOutl"+c.id.substr(4)),document.getElementById("pic"+c.id.substr(4)),true)}if(m_Course.LOArray[a].Enabled==1){if(e.className=="Node_Disabled")e.className="Node"}else if(e.className=="Node")e.className="Node_Disabled";b="";b=m_Course.AllowTracking?m_Course.LOArray[a].SuccessStatus==
1?sco_passed.src:m_Course.LOArray[a].SuccessStatus==2?sco_failed.src:m_Course.LOArray[a].CompletionStatus==1?sco_completed.src:m_Course.LOArray[a].CompletionStatus==2?sco_incomplete.src:m_Course.LOArray[a].CompletionStatus==3?sco_notStarted.src:m_Course.LOArray[a].CompletionStatus==4?sco_notStarted.src:sco_empty.src:sco_empty.src;d.src=b;d.alt=GetStatus(m_Course.LOArray[a].CompletionStatus,m_Course.LOArray[a].SuccessStatus);d.title=d.alt;d=document.getElementById("imgOutl"+m_Course.LOArray[a].NodeID);
b="";if(m_Course.LOArray[a].VisibleChildrenCount>0){if(m_Course.LOArray[a].NodeID==m_Course.CourseLearningObjectID)b="outl_ro";else if(document.getElementById("item"+m_Course.LOArray[a].NodeID))b=document.getElementById("item"+m_Course.LOArray[a].NodeID).style.display==""?m_Course.LOArray[a].IsLastChild==0?"outl_mo":"outl_lo":m_Course.LOArray[a].IsLastChild==0?"outl_mc":"outl_lc";d.onclick=function(){AvailbleStuff(this.id.substring(7));return false}}else{b=m_Course.LOArray[a].NodeID==m_Course.CourseLearningObjectID?
"outl_r":m_Course.LOArray[a].IsLastChild==0?"outl_m":"outl_l";d.onclick=function(){return false}}d.src=expandimages[b];d.name=b}}}
function LaunchContent(a){if(contentframe==undefined)setTimeout("LaunchContent("+a+")",100);else{if(a=="I")contentframe.location.replace("Instruction.aspx?LangID="+document.frmParams.LangID.value+"&PreassessReq="+(m_Course.Preassess!=null&&m_Course.PreassessRequired==1)+"&CourseReq="+(m_Course!=null&&m_Course.SubjectRequired==1)+"&PostassessReq="+(m_Course.Postassess!=null&&m_Course.PostassessRequired==1)+"&HasPreassess="+(m_Course.Preassess!=null)+"&ShowOutline="+get_cookie("ShowOutline_"+document.frmParams.UserID.value));
else{var b;b=a==""?"../Pages/Message.aspx?&LangID="+document.frmParams.LangID.value+"&Message=679":ConcatURLString(applicationPath,"APIAdapter/APIWrapper.aspx?LearningObjectNodeID="+a+"&PathnodeID="+document.frmParams.NodeID.value+"&LangID="+document.frmParams.LangID.value+"&StartPersonal="+document.frmParams.StartPersonal.value+"&AllowTracking="+m_Course.AllowTracking+"&FromKpath=true&rnd="+(Math.round(Math.random()*1E5)+1));contentframe.location.replace(b)}if(noteAvail)a=="I"||a.length>4&&a.substring(0,
4)=="PRE_"||a.length>5&&a.substring(0,5)=="POST_"?UpdateContentHeader(a,m_Course.HasAssessmentCompleted,0):PageMethods.GetNoteCount(parseInt(document.frmParams.UserID.value),parseInt(a),GetNoteCountOnSucceeded,GetNoteCountOnFailed);else UpdateContentHeader(a,m_Course.HasAssessmentCompleted,0)}}function GetNoteCountOnSucceeded(a){UpdateContentHeader(m_Course.DeliveryNodeID,m_Course.HasAssessmentCompleted,parseInt(a))}
function GetNoteCountOnFailed(){UpdateContentHeader(m_Course.DeliveryNodeID,m_Course.HasAssessmentCompleted,0)}function ConcatURLString(a,b){if(a=="")return b;if(b=="")return a;if(a.charAt(a.length-1)=="/"||a.charAt(a.length-1)=="\\")a=a.substring(0,a.length-1);if(b.charAt(0)=="/"||b.charAt(0)=="\\")b=b.substring(1,b.length-1);return a+"/"+b}
function EventMouseOver(a){if(m_Course.PlayMode==2)if(!m_Course.IsPrevOrNextItem(a))return;if(document.getElementById("link"+a).className=="Node"||document.getElementById("link"+a).className=="Node_Highlight"||document.getElementById("link"+a).className=="OutlinePanelHeaderText"||document.getElementById("link"+a).className=="OutlinePanelHeaderTextHighlight")ChangeStyle(document.getElementById("link"+a),true);return false}
function EventMouseOut(a){if(document.getElementById("link"+a).className=="Node"||document.getElementById("link"+a).className=="Node_Highlight"||document.getElementById("link"+a).className=="OutlinePanelHeaderText"||document.getElementById("link"+a).className=="OutlinePanelHeaderTextHighlight")ChangeStyle(document.getElementById("link"+a),false);return false}
function ChangeStyle(a,b){if(b){a.style.textDecoration="underline";a.style.cursor="pointer"}else{a.style.textDecoration="none";a.style.cursor="default"}}function EventKeydown(a){switch(window.event?window.event.keyCode:a.which){case 40:outline_MoveNext();break;case 37:outline_MovePrev();break;case 39:outline_MoveNext();break;case 38:outline_MovePrev();break;case 9:return true}return false}
function DisplayInfo(a,b){var c=document.getElementById("lblLongInfo"+a),d=document.getElementById("imgLongInfo"+a),e=document.getElementById("lblShortInfo"+a),g=document.getElementById("imgShortInfo"+a);if(b==0){c.style.display="";d.style.display="";e.style.display="none";g.style.display="none"}else{c.style.display="none";d.style.display="none";e.style.display="";g.style.display=""}if(m_Course.Preassess!=null)if(a==m_Course.Preassess.NodeID&&m_Course.Preassess.CompletionStatus==1){c=new Date;c.setTime((new Date).getTime()+
31536E6);set_cookie("PreassessCompletionCollapse_"+document.frmParams.UserID.value,b,c)}ResizePanels()}
function AvailbleStuff(a){var b;b="imgOutl"+a;if(document.getElementById("item"+a))if(document.getElementById("item"+a).style.display=="none"){document.getElementById("item"+a).style.display="";SetPlusMinus(document.getElementById(b),document.getElementById("pic"+a),false)}else{document.getElementById("item"+a).style.display="none";SetPlusMinus(document.getElementById(b),document.getElementById("pic"+a),true)}return false}function ReloadMe(){ResizeMe(true)}
function ChangeColor(a,b){if(b){a.style.backgroundColor=HoverBG;if(document.getElementById("link"+a.id.substr(1)).className=="Node")a.style.cursor="pointer"}else{a.style.cursor="default";a.style.backgroundColor=m_HighLightItem!=null&&a.id==m_HighLightItem.id?HiLiteBG:StdBG}}
function ResizeMe(a){if(GetWindowWidth()>0)if(!blnIsContentExport)if(get_cookie("ShowOutline_"+document.frmParams.UserID.value).toLowerCase()=="true"){if(a&&PostOutlineCookie){a=new Date;a.setTime((new Date).getTime()+31536E6);blnIsSearch?set_cookie("SearchWidth_"+document.frmParams.UserID.value,GetWindowWidth(),a):set_cookie("OutlineWidth_"+document.frmParams.UserID.value,GetWindowWidth(),a)}PostOutlineCookie=true}}
function outline_MovePrev(){m_NavRequest=NAV_REQUEST_PREVIOUS;m_ChoiceTargetNodeID=0;if(m_HighLightItem==null){m_Course.DeliveryNodeID=m_Course.FindFirstItem();GotoDeliveryLearningObject(m_Course.DeliveryNodeID,NAV_REQUEST_PREVIOUS);LaunchContent(m_Course.DeliveryNodeID)}else{var a=m_Course.DeliveryNodeID;m_Course.DeliveryNodeID=m_Course.FindPrevItem();if(m_Course.DeliveryNodeID!=a){GotoDeliveryLearningObject(m_Course.DeliveryNodeID,NAV_REQUEST_PREVIOUS);LaunchContent(m_Course.DeliveryNodeID)}}}
function UnloadContent(){contentframe.location.replace("../Pages/Loading.aspx?LangID="+document.frmParams.LangID.value)}
function outline_MoveNext(){m_NavRequest=NAV_REQUEST_CONTINUE;m_ChoiceTargetNodeID=0;if(m_HighLightItem==null){m_Course.DeliveryNodeID=m_Course.FindFirstItem();GotoDeliveryLearningObject(m_Course.DeliveryNodeID,NAV_REQUEST_CONTINUE);LaunchContent(m_Course.DeliveryNodeID)}else if(m_Course.DeliveryNodeID.length>4&&m_Course.DeliveryNodeID.substring(0,4)=="PRE_"&&m_Course.HasCourse==false&&m_Course.HasPostAssess==false)NavBack();else{var a=m_Course.FindNextItem();if(a=="")confirm(strEndOfOutlineMsg)&&
NavBack();else{m_Course.DeliveryNodeID=a;GotoDeliveryLearningObject(m_Course.DeliveryNodeID,NAV_REQUEST_CONTINUE);LaunchContent(m_Course.DeliveryNodeID)}}}function GoToItem(a){window.location.hash="a"+a}function ConfirmResult(a){if(a==1)StartPersonalCourse();else a==2?StartFullCourse():NavBack()}
function Nav(a){switch(a){case "continue":if(m_Course.DeliveryNodeID.length>4&&m_Course.DeliveryNodeID.substring(0,4)=="PRE_")if(m_Course.AllowPersonal)CustomConfirm(m_strConfirmHeader,m_strConfirmMessagePre,m_strShowPersonal,m_strShowFull,"",ConfirmResult);else m_Course.HasCourse==true||m_Course.HasPostAssess==true?outline_MoveNext():setTimeout("NavBack();",1);else if(m_Course.DeliveryNodeID.length>5&&m_Course.DeliveryNodeID.substring(0,5)=="POST_")if(m_Course.AllowPersonal)CustomConfirm(m_strConfirmHeader,
m_strConfirmMessagePost,m_strShowPersonal,m_strShowFull,m_strExitActivity,ConfirmResult);else if(m_Course.HasCourse==true)CustomConfirm(m_strViewContent,m_strConfirmViewContent,"",m_strShowSubject,m_strExitActivity,ConfirmResult);else confirm(strEndOfOutlineMsg)?setTimeout("NavBack();",1):Outline_Select(m_Course.DeliveryNodeID,true);else outline_MoveNext();break;case "previous":outline_MovePrev();break;case "exit":case "exitAll":case "abandon":case "abandonAll":case "_none_":break;default:if(a.substring(a.length-
6,a.length)=="choice"){a=a.substring(8,a.indexOf("}"));a=GetNodeIDByGUID(a);Outline_Select(a,false)}}}function StartPersonalCourse(){document.frmParams.StartPersonal.value="true";document.frmParams.elements.StartPersonal.value="true";StartPersonalWithGUID("true",m_Course.CourseLearningObjectID)}
function StartFullCourse(){document.frmParams.StartPersonal.value="false";document.frmParams.elements.StartPersonal.value="false";document.frmParams.StartPersonal.value=="false"?Outline_Select(m_Course.CourseLearningObjectID,false):StartPersonalWithGUID("false",m_Course.CourseLearningObjectID)}function GetNodeIDByGUID(a){for(var b=0;b<m_Course.LOArray.length;b++)if(m_Course.LOArray[b].GUID==a)return m_Course.LOArray[b].NodeID;return""}function SignalUserActivity(){SetInactivityTimeout()}
function EnableNavButton(a,b){b==0?DisplayNavButton(a,false):DisplayNavButton(a,true)}function Unload(){navigator.userAgent.match(/iPad/i)!=null||PageMethods.CourseRollupProcess(document.frmParams.UserID.value,m_Course.CourseLearningObjectID,document.frmParams.StartPersonal.value)}document.onkeydown=EventKeydown;
